# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180109_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(default='img/emptyPP.png', upload_to='img/'),
        ),
    ]
