# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180109_1052'),
        ('blog', '0003_auto_20180109_1221'),
    ]

    operations = [
    ]
